// products/sections/showcase/showcase-data.ts

import type {ShowcaseProduct} from "./../../showcase-types";

export const ALL_PRODUCTS: ShowcaseProduct[] = [
  {
    id: "1",
    name: "Modern Sauna – Valhalla",
    slug: "modern-sauna-valhalla",
    productType: "Barrel Sauna",
    woodType: "Thermowood",
    brand: "Showcase",
    heatingType: "Electric",
    seatingCapacity: "4",
    price: 5500,
    currency: "CAD",
    badge: "READY TO SHIP NOW",
    extendedInfo: "Extended View",
    rating: 5,
    reviewsCount: 89,
    thumbnailUrl:
      "https://i.ibb.co.com/xKZYc1VC/SADSFSDSDFSD-1-1.png",
  },
  {
    id: "2",
    name: "Valhalla Mini Outdoor Sauna",
    slug: "valhalla-mini-outdoor",
    productType: "Barrel Sauna",
    woodType: "Thermowood",
    brand: "Showcase",
    heatingType: "Electric",
    seatingCapacity: "2",
    price: 4990,
    currency: "CAD",
    badge: "READY TO SHIP NOW",
    extendedInfo: "Compact Footprint",
    rating: 4.8,
    reviewsCount: 41,
    thumbnailUrl:
      "https://i.ibb.co.com/7dzNqdXW/suasdasdna-1.png",
  },
  {
    id: "3",
    name: "8 FT Thermowood Scenic View Barrel Sauna",
    slug: "8ft-thermowood-scenic-view",
    productType: "Scenic View Sauna",
    woodType: "Thermowood",
    brand: "Showcase",
    heatingType: "Electric",
    seatingCapacity: "6",
    price: 7290,
    currency: "CAD",
    badge: "READY TO SHIP NOW",
    extendedInfo: "Panoramic Front Glass",
    rating: 4.9,
    reviewsCount: 63,
    thumbnailUrl:
      "https://i.ibb.co.com/xKZYc1VC/SADSFSDSDFSD-1-1.png",
  },
  {
    id: "4",
    name: "Commercial Barrel Sauna – Nordic Spa",
    slug: "commercial-barrel-nordic",
    productType: "Commercial Sauna",
    woodType: "Cedar",
    brand: "Showcase Pro",
    heatingType: "Electric",
    seatingCapacity: "8",
    price: 11900,
    currency: "CAD",
    badge: "READY TO SHIP NOW",
    extendedInfo: "Designed for heavy use",
    rating: 4.7,
    reviewsCount: 37,
    thumbnailUrl:
      "https://i.ibb.co.com/7dzNqdXW/suasdasdna-1.png",
  },
  {
    id: "5",
    name: "Luxury Cabin Sauna – Aurora",
    slug: "luxury-cabin-aurora",
    productType: "Luxury Sauna",
    woodType: "Cedar",
    brand: "Aurora",
    heatingType: "Hybrid",
    seatingCapacity: "6",
    price: 13990,
    currency: "CAD",
    badge: "READY TO SHIP NOW",
    extendedInfo: "Interior mood lighting",
    rating: 5,
    reviewsCount: 22,
    thumbnailUrl:
      "https://i.ibb.co.com/xKZYc1VC/SADSFSDSDFSD-1-1.png",
  },
  {
    id: "6",
    name: "Scenic View Barrel Sauna – Lakefront",
    slug: "scenic-view-lakefront",
    productType: "Scenic View Sauna",
    woodType: "Spruce",
    brand: "Showcase",
    heatingType: "Wood-Burning",
    seatingCapacity: "4",
    price: 6990,
    currency: "CAD",
    badge: "READY TO SHIP NOW",
    extendedInfo: "Perfect for cabins",
    rating: 4.6,
    reviewsCount: 18,
    thumbnailUrl:
      "https://i.ibb.co.com/7dzNqdXW/suasdasdna-1.png",
  },
];
